version: "3.1"

x-app-defaults: &app-defaults
  image: janekl/godoo:latest
  networks:
    - odoo-net
  restart: unless-stopped

x-db-defaults: &db-defaults
  image: postgres:15.0
  networks:
    - odoo-net
  ports:
    - 5432:5432
  environment:
    - POSTGRES_PASSWORD=odoo16@2023
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres 
    - PGDATA=/data
  restart: unless-stopped

services:
  odoo:
    user: root
    container_name: odoo-stack
    image: odoo:16.0
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons-extra:/mnt/addons-extra
      - ./etc:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 10016:8069
      # - 20016:8072 # live chat
    tty: true
    command: --
    environment:
      - HOST=db 
      - USER=odoo
      - PASSWORD=odoo16@2023
    networks:
      - odoo-net
    depends_on:
      - db
    restart: always
  db:
    <<: *db-defaults
    container_name: db-stack
    user: root
    tty: true
    command: "postgres -c config_file=/config/postgresql.conf"
    volumes:
      - ./pgdata:/data
      - ./config:/config/
      - type: volume 
        source: odoo-web-data
        target: /data

  app:
    <<: *app-defaults
    container_name: godoo-stack
    volumes:
      - ./godoo:$HOME/go/bin/godoo
    tty: true
    command: --
    depends_on:
      - db
    restart: always

networks:
  odoo-net:
    driver: bridge

volumes:
  odoo-web-data: